version: '3'

services:
  client:
    environment:
      - SERVER_PORT=4000
    build:
        dockerfile: Dockerfile.dev
        context: ./client
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    environment:
      PORT: 4000
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
  mongo:
    image: mongo
    restart: always
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8000:80
  